# Generated by Django 4.2 on 2023-05-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_userorder_products_alter_userorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Realizado", "Realizado"),
                    ("Em andamento", "Andamento"),
                    ("Entregue", "Entregue"),
                ],
                default="Em andamento",
                max_length=20,
            ),
        ),
    ]
